<?php

use Illuminate\Database\Seeder;
use App\Models\Cantone;

class CantoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Cantone::truncate();

        $cantone = new Cantone;
        $cantone->provincia_id = '01';
        $cantone->canton = 'Cuenca';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '01';
        $cantone->canton = 'Girón';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '01';
        $cantone->canton = 'Gualaceo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '01';
        $cantone->canton = 'Nabón';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '01';
        $cantone->canton = 'Paute';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '01';
        $cantone->canton = 'Pucará';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '01';
        $cantone->canton = 'San Fernando';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '01';
        $cantone->canton = 'Santa Isabel';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '01';
        $cantone->canton = 'Sigsig';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '01';
        $cantone->canton = 'Oña';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '01';
        $cantone->canton = 'Chordeleg';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '01';
        $cantone->canton = 'El Pan';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '01';
        $cantone->canton = 'Sevilla de Oro';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '01';
        $cantone->canton = 'Guachapala';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '01';
        $cantone->canton = 'Camilo Ponce Enríquez';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '02';
        $cantone->canton = 'Guaranda';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '02';
        $cantone->canton = 'Chillanes';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '02';
        $cantone->canton = 'Chimbo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '02';
        $cantone->canton = 'Echeandía';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '02';
        $cantone->canton = 'San Miguel';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '02';
        $cantone->canton = 'Caluma';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '02';
        $cantone->canton = 'Las Naves';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '03';
        $cantone->canton = 'Azogues';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '03';
        $cantone->canton = 'Biblían';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '03';
        $cantone->canton = 'Cañar';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '03';
        $cantone->canton = 'La Troncal';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '03';
        $cantone->canton = 'El Tambo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '03';
        $cantone->canton = 'Déleg';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '03';
        $cantone->canton = 'Suscal';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '04';
        $cantone->canton = 'Tulcán';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '04';
        $cantone->canton = 'Bolívar';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '04';
        $cantone->canton = 'Espejo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '04';
        $cantone->canton = 'Mira';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '04';
        $cantone->canton = 'Montúfar';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '04';
        $cantone->canton = 'San Pedro de Huaca';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '05';
        $cantone->canton = 'Latacunga';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '05';
        $cantone->canton = 'La Maná';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '05';
        $cantone->canton = 'Pangua';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '05';
        $cantone->canton = 'Pujíli';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '05';
        $cantone->canton = 'Salcedo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '05';
        $cantone->canton = 'Saquisilí';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '05';
        $cantone->canton = 'Sigchos';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '06';
        $cantone->canton = 'Riobamba';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '06';
        $cantone->canton = 'Alausí';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '06';
        $cantone->canton = 'Colta';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '06';
        $cantone->canton = 'Chambo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '06';
        $cantone->canton = 'Chunchi';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '06';
        $cantone->canton = 'Guamote';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '06';
        $cantone->canton = 'Guano';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '06';
        $cantone->canton = 'Pallatanga';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '06';
        $cantone->canton = 'Penipe';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '06';
        $cantone->canton = 'Cumandá';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '07';
        $cantone->canton = 'Machala';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '07';
        $cantone->canton = 'Arenillas';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '07';
        $cantone->canton = 'Atahualpa';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '07';
        $cantone->canton = 'Balsas';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '07';
        $cantone->canton = 'Chilla';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '07';
        $cantone->canton = 'El Guabo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '07';
        $cantone->canton = 'Huaquillas';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '07';
        $cantone->canton = 'Marcabelí';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '07';
        $cantone->canton = 'Pasaje';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '07';
        $cantone->canton = 'Piñas';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '07';
        $cantone->canton = 'Portovelo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '07';
        $cantone->canton = 'Santa Rosa';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '07';
        $cantone->canton = 'Zaruma';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '07';
        $cantone->canton = 'Las Lajas';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '08';
        $cantone->canton = 'Esmeraldas';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '08';
        $cantone->canton = 'Eloy Alfaro';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '08';
        $cantone->canton = 'Muisne';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '08';
        $cantone->canton = 'Quinindé';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '08';
        $cantone->canton = 'San Lorenzo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '08';
        $cantone->canton = 'Atacames';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '08';
        $cantone->canton = 'Río Verde';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Guayaquil';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Alfredo Baquerizo Moreno (Juján)';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Balao';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Balzar';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Colimes';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Daule';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Durán';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'El Empalme';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'El Triunfo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Milagro';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Naranjal';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Naranjito';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Palestina';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Pedro Carbo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Samborondón';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Santa Lucía';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Salitre';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'San Jacinto de Yaguachi';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Playas';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Simón Bolívar';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Coronel Marcelino Maridueña';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Lomas de Sargentillo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Nobol';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'General Antonio Elizalde';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '09';
        $cantone->canton = 'Isidro Ayora';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '10';
        $cantone->canton = 'Ibarra';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '10';
        $cantone->canton = 'Antonio Ante';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '10';
        $cantone->canton = 'Cotacachi';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '10';
        $cantone->canton = 'Otavalo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '10';
        $cantone->canton = 'Pimampiro';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '10';
        $cantone->canton = 'San Miguel de Urcuquí';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '11';
        $cantone->canton = 'Loja';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '11';
        $cantone->canton = 'Calvas';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '11';
        $cantone->canton = 'Catamayo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '11';
        $cantone->canton = 'Celica';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '11';
        $cantone->canton = 'Chaguarpamba';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '11';
        $cantone->canton = 'Espíndola';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '11';
        $cantone->canton = 'Gonzanamá';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '11';
        $cantone->canton = 'Macará';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '11';
        $cantone->canton = 'Paltas';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '11';
        $cantone->canton = 'Puyango';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '11';
        $cantone->canton = 'Saraguro';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '11';
        $cantone->canton = 'Sozoranga';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '11';
        $cantone->canton = 'Zapotillo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '11';
        $cantone->canton = 'Pindal';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '11';
        $cantone->canton = 'Quilanga';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '11';
        $cantone->canton = 'Olmedo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '12';
        $cantone->canton = 'Babahoyo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '12';
        $cantone->canton = 'Baba';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '12';
        $cantone->canton = 'Montalvo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '12';
        $cantone->canton = 'Pueblo Viejo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '12';
        $cantone->canton = 'Quevedo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '12';
        $cantone->canton = 'Urdaneta';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '12';
        $cantone->canton = 'Ventanas';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '12';
        $cantone->canton = 'Vínces';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '12';
        $cantone->canton = 'Palenque';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '12';
        $cantone->canton = 'Buena Fé';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '12';
        $cantone->canton = 'Valencia';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '12';
        $cantone->canton = 'Mocache';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '12';
        $cantone->canton = 'Quinsaloma';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = 'Portoviejo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = 'Bolívar';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = 'Chone';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = 'El Carmen';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = 'Flavio Alfaro';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = 'Jipijapa';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = 'Junín';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = 'Manta';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = 'Montecristi';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = 'Paján';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = 'Pichincha';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = 'Rocafuerte';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = 'Santa Ana';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = 'Sucre';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = 'Tosagua';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = '24 de Mayo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = 'Pedernales';
        $cantone->save();
        $cantone = new Cantone;
       $cantone->provincia_id = '13';
        $cantone->canton = 'Olmedo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = 'Puerto López';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = 'Jama';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = 'Jaramijó';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '13';
        $cantone->canton = 'San Vicente';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '14';
        $cantone->canton = 'Morona';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '14';
        $cantone->canton = 'Gualaquiza';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '14';
        $cantone->canton = 'Limón Indanza';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '14';
        $cantone->canton = 'Logroño';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '14';
        $cantone->canton = 'Palora';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '14';
        $cantone->canton = 'Santiago de Méndez';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '14';
        $cantone->canton = 'Sucúa';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '14';
        $cantone->canton = 'Huamboya';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '14';
        $cantone->canton = 'San Juan Bosco';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '14';
        $cantone->canton = 'Taisha';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '14';
        $cantone->canton = 'Pablo Sexto';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '14';
        $cantone->canton = 'Tiwintza';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '15';
        $cantone->canton = 'Tena';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '15';
        $cantone->canton = 'Archidona';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '15';
        $cantone->canton = 'El Chaco';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '15';
        $cantone->canton = 'Quijos';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '15';
        $cantone->canton = 'Carlos Julio Arosemna Tola';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '16';
        $cantone->canton = 'Pastaza';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '16';
        $cantone->canton = 'Mera';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '16';
        $cantone->canton = 'Santa Clara';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '16';
        $cantone->canton = 'Arajuno';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '17';
        $cantone->canton = 'Quito';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '17';
        $cantone->canton = 'Cayambe';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '17';
        $cantone->canton = 'Mejía';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '17';
        $cantone->canton = 'Pedro Moncayo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '17';
        $cantone->canton = 'Rumiñahui';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '17';
        $cantone->canton = 'San Miguel de los Bancos';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '17';
        $cantone->canton = 'Pedro Vicente Maldonado';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '17';
        $cantone->canton = 'Puerto Quito';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '18';
        $cantone->canton = 'Ambato';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '18';
        $cantone->canton = 'Baños de Agua Santa';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '18';
        $cantone->canton = 'Cevallos';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '18';
        $cantone->canton = 'Mocha';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '18';
        $cantone->canton = 'Patate';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '18';
        $cantone->canton = 'Quero';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '18';
        $cantone->canton = 'San Pedro de Pelileo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '18';
        $cantone->canton = 'Santiago de Píllaro';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '18';
        $cantone->canton = 'Tisaleo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '19';
        $cantone->canton = 'Zamora';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '19';
        $cantone->canton = 'Chinchipe';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '19';
        $cantone->canton = 'Nangaritza';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '19';
        $cantone->canton = 'Yacuambi';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '19';
        $cantone->canton = 'Yantzaza';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '19';
        $cantone->canton = 'El Pangui';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '19';
        $cantone->canton = 'Centinela del Cóndor';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '19';
        $cantone->canton = 'Palanda';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '19';
        $cantone->canton = 'Paquisha';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '20';
        $cantone->canton = 'San Cristóbal';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '20';
        $cantone->canton = 'Isabela';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '20';
        $cantone->canton = 'Santa Cruz';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '21';
        $cantone->canton = 'Lago Agrio';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '21';
        $cantone->canton = 'Gonzalo Pizarro';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '21';
        $cantone->canton = 'Putumayo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '21';
        $cantone->canton = 'Shushudindi';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '21';
        $cantone->canton = 'Sucumbíos';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '21';
        $cantone->canton = 'Cascales';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '21';
        $cantone->canton = 'Cuyabeno';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '22';
        $cantone->canton = 'Orellana';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '22';
        $cantone->canton = 'Aguarico';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '22';
        $cantone->canton = 'La Joya de los Sachas';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '22';
        $cantone->canton = 'Loreto';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '23';
        $cantone->canton = 'Santo Domingo';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '23';
        $cantone->canton = 'La Concordia';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '24';
        $cantone->canton = 'Santa Elena';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '24';
        $cantone->canton = 'La Libertad';
        $cantone->save();
        $cantone = new Cantone;
        $cantone->provincia_id = '24';
        $cantone->canton = 'Salinas';
        $cantone->save();
    
    }
}
